server:
  port: 8081
  context-path: /cms

spring:
    datasource:
        name: mcms
        url: jdbc:mysql://192.168.1.110:3306/mcms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        druid:
          aop-patterns: com.alibaba.druid.spring.boot.demo.service.*
          max-active: 10
          min-evictable-idle-time-millis: 100000
          filter:
            stat:
              db-type: mysql
              log-slow-sql: true
              slow-sql-millis: 2000
            wall:
              enabled: true
              db-type: mysql
              config:
                delete-allow: true
                drop-table-allow: true
    aop:
      proxy-target-class: true
    http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
#    thymeleaf:
#          cache: false
#          check-template-location: true
#          content-type: text/html
#          enabled: true
#          encoding: utf-8
#          excluded-view-names:
#          mode: HTML5
#          prefix: classpath:/templates/
#          suffix: .html
    session:
      store-type: none

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fnsco.model
